# Generated by Django 2.1.2 on 2018-11-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeSearch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('expertise', models.TextField()),
                ('number', models.IntegerField()),
            ],
        ),
    ]
