# Generated by Django 2.1.2 on 2018-11-10 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeSearch', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('number', models.IntegerField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
