# Generated by Django 2.1.2 on 2018-11-10 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgeSearch', '0003_ticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='time',
            new_name='submitTime',
        ),
    ]
